import { useEffect, useMemo, useState } from 'react';
import { SITE_DATA as data } from '../data.js';

const Brand = () => <a className="brand" href="#top"><span className="brand-mark"><img src={data.business.logo} alt="Ujala Trading Concern logo" /></span><span><strong>{data.business.name}</strong><small>{data.business.tagline}</small></span></a>;

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState(null);
  const whatsapp = data.business.whatsapp.replace(/\D/g, '');
  const whatsappUrl = useMemo(() => `https://wa.me/${whatsapp}?text=${encodeURIComponent('Hello, I would like to ask about your products and services.')}`, [whatsapp]);
  const directionsUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(data.business.mapQuery)}`;
  const productMessage = selectedProduct ? `https://wa.me/${whatsapp}?text=${encodeURIComponent(`Hello, I would like to enquire about ${selectedProduct.name}.`)}` : whatsappUrl;

  useEffect(() => { document.body.classList.toggle('menu-open', menuOpen || selectedProduct); return () => document.body.classList.remove('menu-open'); }, [menuOpen, selectedProduct]);
  useEffect(() => { const close = e => e.key === 'Escape' && setSelectedProduct(null); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
  const WhatsAppLink = ({ children, className = 'button' }) => <a className={className} href={whatsappUrl} target="_blank" rel="noopener noreferrer">{children}</a>;

  return <>
    <header className="site-header" id="top"><div className="container nav-wrap"><Brand /><button className="menu-toggle" aria-label="Open navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /><span /></button><nav className={`nav-links ${menuOpen ? 'open' : ''}`}>{['about','services','products','work','contact'].map(item => <a key={item} href={`#${item}`} onClick={() => setMenuOpen(false)}>{item === 'work' ? 'Recent work' : item[0].toUpperCase()+item.slice(1)}</a>)}<WhatsAppLink className="button button-small">Chat with us ↗</WhatsAppLink></nav></div></header>
    <main>
      <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">DTF printing · Labels · Garment supplies</p><h1>Every detail your garment deserves.</h1><p className="hero-text">From vibrant DTF prints to dependable trims, labels and packaging, we provide the finishing essentials that turn a garment into a complete, professional product.</p><div className="hero-actions"><WhatsAppLink>Send an enquiry ↗</WhatsAppLink><a className="button button-secondary" href="#products">Explore products ↓</a></div><a className="hero-phone" href={`tel:${data.business.phoneLink}`}>Need quick assistance? <strong>Call {data.business.phone}</strong></a><div className="hero-highlights">{data.hero.highlights.map(item => <span key={item}><i>✓</i>{item}</span>)}</div></div><div className="hero-visual"><div className="image-frame"><img src={data.hero.image} alt="Garment accessories and tailoring materials" /></div><img className="hero-detail hero-detail-one" src="assets/tags.jpg" alt="Custom clothing tags" /><img className="hero-detail hero-detail-two" src="assets/thread.jpg" alt="Colorful sewing threads" /><div className="floating-card"><span className="pulse" /><div><small>Ready to help</small><strong>Custom & bulk orders</strong></div></div><span className="hero-stamp">Quality<br/>you can<br/>feel</span></div></div></section>
      <section className="trust-strip"><div className="marquee">{['Zippers','Dori','Tags','Elastic','Thread','DTF Stickers','Packaging'].map(item => <span key={item}>✦ {item}</span>)}</div></section>
      <section className="section about" id="about"><div className="container about-grid"><div><p className="section-label">About Ujala</p><h2>{data.about.title}</h2></div><div><p className="large-copy">{data.about.text}</p><div className="stats">{data.about.stats.map(stat => <div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div></div></div></section>
      <section className="trust-points"><div className="container trust-grid">{data.trustPoints.map((item,i) => <div key={item}><span>0{i+1}</span><strong>{item}</strong></div>)}</div></section>
      <section className="section services" id="services"><div className="container"><Heading label="What we do" title="Professional finishing, tailored to your needs." text="Reliable materials, careful workmanship and practical support for every stage of your production process."/><div className="service-list">{data.services.map(service => <article className="service-card" key={service.number}><span className="service-number">{service.number}</span><div><h3>{service.title}</h3><p>{service.description}</p></div><img src={service.image} alt={service.title} loading="lazy" /></article>)}</div></div></section>
      <section className="section products" id="products"><div className="container"><Heading label="Our product range" title="Everything you need for the perfect finish." text="Select a product to see example options. Replace the demo details at any time in data.js."/><div className="product-grid">{data.products.map((product,index) => <button className="product-card" key={`${product.name}-${index}`} onClick={() => setSelectedProduct(product)}><div className="product-image"><img src={product.image} alt={product.name} loading="lazy" /></div><div><small>{product.category}</small><h3>{product.name}</h3><span>View details →</span></div></button>)}</div></div></section>
      <section className="section work" id="work"><div className="container"><Heading label="Recent work" title="A closer look at what we do." text="Demo project images are shown here. Replace them with photographs of your completed customer orders."/><div className="work-grid">{data.recentWork.map((item,i) => <figure className={i===0 ? 'work-featured':''} key={item.title}><img src={item.image} alt={item.title} loading="lazy"/><figcaption><small>{item.type}</small><strong>{item.title}</strong></figcaption></figure>)}</div></div></section>
      <section className="section testimonials"><div className="container"><Heading label="Customer feedback" title="Built on helpful, dependable service." text="These are demo testimonials. Replace them with verified customer feedback when available."/><div className="testimonial-grid">{data.testimonials.map(item => <blockquote key={item.name}><span>“</span><p>{item.quote}</p><footer><strong>{item.name}</strong><small>{item.company}</small></footer></blockquote>)}</div></div></section>
      <section className="cta-section"><div className="container cta-card"><div><p className="section-label light">Let’s get started</p><h2>Planning your next garment order?</h2></div><div><p>Share your design, quantity or material requirements. We’ll help you find a practical option for your timeline and budget.</p><WhatsAppLink className="button button-light">Discuss your requirements ↗</WhatsAppLink></div></div></section>
      <section className="section contact" id="contact"><div className="container contact-grid"><div><p className="section-label">Visit or contact us</p><h2>See the quality for yourself.</h2><p className="large-copy">Visit our Birgunj shop to explore the collection, compare materials and view product samples.</p><div className="contact-links"><a className="contact-call" href={`tel:${data.business.phoneLink}`}>☎ {data.business.phone}</a><a href={directionsUrl} target="_blank" rel="noopener noreferrer">Get directions ↗</a></div><div className="map-card"><div className="map-pin">⌖</div><div><strong>Find us in Birgunj</strong><p>{data.business.address}</p></div><a href={directionsUrl} target="_blank" rel="noopener noreferrer">Open map</a></div></div><div className="contact-panel"><div><small>Shop address</small><p>{data.business.address}</p></div><div><small>Opening hours</small><div>{data.hours.map(item => <p key={item.day}><span>{item.day}</span><strong>{item.time}</strong></p>)}</div></div></div></div></section>
    </main>
    <footer className="site-footer"><div className="container footer-wrap"><img className="footer-logo" src={data.business.logo} alt="Ujala logo"/><p>Garment accessories, DTF printing & heat transfer solutions in Birgunj.</p><a href="#top">Back to top ↑</a></div></footer>
    <div className="floating-contact" aria-label="Quick contact"><a href={`tel:${data.business.phoneLink}`} aria-label="Call us">☎</a><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp us">WA</a></div>
    {selectedProduct && <div className="modal-backdrop" onMouseDown={() => setSelectedProduct(null)}><div className="product-modal" role="dialog" aria-modal="true" aria-label={`${selectedProduct.name} details`} onMouseDown={e => e.stopPropagation()}><button className="modal-close" onClick={() => setSelectedProduct(null)} aria-label="Close">×</button><img src={selectedProduct.image} alt={selectedProduct.name}/><div className="modal-content"><small>{selectedProduct.category}</small><h2>{selectedProduct.name}</h2><dl><div><dt>Available options</dt><dd>{selectedProduct.variants}</dd></div><div><dt>Example minimum order</dt><dd>{selectedProduct.minimumOrder}</dd></div><div><dt>Customization</dt><dd>{selectedProduct.customization}</dd></div></dl><p className="demo-note">Demo information—edit these details in data.js.</p><a className="button" href={productMessage} target="_blank" rel="noopener noreferrer">Ask about {selectedProduct.name} ↗</a></div></div></div>}
  </>;
}

function Heading({label,title,text}) { return <div className="section-heading"><div><p className="section-label">{label}</p><h2>{title}</h2></div><p>{text}</p></div>; }
